updates: 
  - commit-message: 
      include: scope
      prefix: chore
    directory: /
    labels: 
      - dependencies
    open-pull-requests-limit: 99
    package-ecosystem: npm
    schedule: 
      interval: daily
      time: "06:00"
      timezone: Asia/Jakarta
    target-branch: master
  - commit-message: 
      include: scope
      prefix: ci
    directory: /
    labels: 
      - gh-actions
      - dependencies
    open-pull-requests-limit: 99
    package-ecosystem: github-actions
    schedule: 
      interval: daily
      time: "06:00"
      timezone: Asia/Jakarta
    target-branch: master
version: 2